#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

cp ../bin/apm-prom-go-demo .
docker build -t ${REPO}/apm-prom-go-demo:${TAG} .

echo Built ${REPO}/apm-prom-go-demo:${TAG}
